stages:
  train_data:
    cmd: python hisia/models/generate_data.py --config=params.yaml
    params:
      - data
      - train
    deps:
      - hisia/models/generate_data.py
      - data/data_custom.json
      - data/data.json
      - data/steffan267_SAM.json
    outs:
      - hisia/data/train/train_data.json
      - hisia/data/test/test_data.json
  
  train_model:
    cmd: python hisia/models/model_train.py
    deps:
      - hisia/models/model_train.py
      - hisia/data/train/train_data.json
    params:
      - data
      - train
    outs:
      - hisia/models/base_model.pkl

  test_model:
    cmd: python hisia/models/model_evaluation.py
    deps:
      - hisia/models/model_evaluation.py
      - hisia/data/test/test_data.json
      - hisia/models/base_model.pkl

  reports:
    cmd: python hisia/models/model_reports.py
    deps:
      - hisia/models/model_reports.py
      - hisia/data/test/test_data.json
      - hisia/data/test/test_data.json
      - hisia/models/base_model.pkl
    plots:
      - hisia/reports/ROC.png:
          cache: false